config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
	scope '/projects/:project_id/', :as => "project" do
		resources :groups, :controller => 'ac_groups', :as => 'ac_groups' do
			resources :fields, :controller => 'ac_fields', :as => 'ac_fields'
		end
	end
end

app/models/ac_field.rb
class AcField < ActiveRecord::Base
  unloadable

  belongs_to :ac_group
  belongs_to :custom_field
end

app/models/ac_group.rb
class AcGroup < ActiveRecord::Base
  unloadable

  has_many :ac_fields, :dependent => :destroy
  belongs_to :tracker
  accepts_nested_attributes_for :ac_fields

  validate :check_name_group_empty
  validate :check_priority_group_empty
  validate :check_priority_field_empty

  # Genera mensaje de error
  def get_error_message
    error_msg = ""
    self.errors.full_messages.each do |msg|
      if error_msg != ""
        error_msg << "<br>"
      end
      error_msg << msg
    end

    error_msg
  end

  private

  # Valida que se ha introducido un nombre para la nueva agrupación.
  def check_name_group_empty
    errors.add :base, l(:"group.error.name_is_empty") if self.name.blank?
  end

  # Valida que se ha introducido una prioridad para esa agrupación.
  def check_priority_group_empty
    errors.add :base, l(:"group.error.priority_is_empty") if self.priority.blank?
  end

  # Valida que se ha introducido una prioridad para los campos personalizados.
  def check_priority_field_empty
    is_blank = false
    self.ac_fields.each do |field|
      is_blank = true if field.priority.blank?
    end

    errors.add :base, l(:"field.error.priority_is_empty") if is_blank == true
  end
  
end

app/controllers/ac_fields_controller.rb
class AcFieldsController < ApplicationController
  unloadable

  before_filter :set_tracker, only: [:destroy]

  def destroy
  	@field = AcField.find params[:id]

  	if @field.destroy
      flash[:notice] = l(:'field.deleted_successfully')
    else
      flash[:error] = l(:'field.deleted_error')
    end
   
  	redirect_to edit_project_ac_group_path(:id => params[:ac_group_id], :project_id => params[:project_id], :tracker_id => @tracker.id)
  end

  private
  def set_tracker
  	@tracker = Tracker.find params[:tracker_id]
  end

 end

app/controllers/ac_groups_controller.rb
class AcGroupsController < ApplicationController
  unloadable

  menu_item :config_agrupacion_campos
  before_filter :find_project_by_project_id, :authorize

  before_filter :set_tracker, only: [:new, :edit]
  before_filter :set_group, only: [:edit, :update, :destroy]
  before_filter :get_custom_fields, only: [:new, :edit]

  def index
  	@trackers = @project.trackers
  end

  def new
  	@group = AcGroup.new

  	# Inicializando para mostrar el fieldset del primer campo personalizado.
  	@field = []
    (0...1).each do |i|
      @field[i] = AcField.new(:id => i) 
    end

     @count_fields = 0
  end

  def create
    @group = AcGroup.new params[:ac_group]

    if @group.save
      flash[:notice] = l(:'group.created_successfully')
      redirect_to project_ac_groups_path(:project_id => @project)
    else
      flash[:error] = @group.get_error_message
      redirect_to action: 'new', :project_id => @project, :tracker_id => params[:ac_group][:tracker_id]
    end
  end

  def edit
    @field = @group.ac_fields.order("priority ASC")
  	@count_fields = @group.ac_fields.count
  end

  def update
    if @group.update_attributes(params[:ac_group]) 
      flash[:notice] = l(:'group.modified_successfully')
      redirect_to project_ac_groups_path(:project_id => @project)
    else
      flash[:error] = @group.get_error_message
      redirect_to action: 'edit', :project_id => @project, :tracker_id => params[:ac_group][:tracker_id]
    end
  end

  def destroy
  	if @group.destroy
      flash[:notice] = l(:'group.deleted_successfully')
    else
      flash[:error] = l(:'group.deleted_error')
    end

    redirect_to project_ac_groups_path(:project_id => @project)
  end

  private
  def set_group
	@group = AcGroup.find params[:id]
  end

  def set_tracker
  	@tracker = Tracker.find params[:tracker_id]
  end

  def get_custom_fields
    @custom_fields_by_tracker = @tracker.custom_fields.uniq.map{|field| [field.name, field.id]}
  end

end

app/views/ac_groups/edit.html.erb
<%= render "ac_groups/partials/form" %>

app/views/ac_groups/index.html.erb
<%= csrf_meta_tag %>
<% content_for :header_tags do %>
   <%= stylesheet_link_tag "/ac_groups.css", :plugin => 'redmine_agrupacion_campos', :media => "screen" %>
<% end %>

<% @trackers.each do |tracker| %>
<fieldset>
	<div class="contextual add-group">
	  <%= link_to '<span class="icon icon-add">'.html_safe+l(:'group.add'), new_project_ac_group_path(:project_id => @project, :tracker_id => tracker.id) %>
	</div>

	<legend><h2><%= tracker.name %></h2></legend>
	<table class="list">
	<thead>
	<tr>
	   <th><%= l(:'group.priority') %></th>
	   <th><%= l(:'group.group_title') %></th>
	   <th><%= l(:'group.count_fields') %></th>
	   <th class="table_groups_permissions"><%= l(:'group.permissions') %></th>
	</tr>
	</thead>
	<tbody>
		<% if tracker.ac_groups.present? %>
			<% tracker.ac_groups.order('priority ASC').each do |group| %>
		    <tr class="<%= cycle("odd", "even") %>">
		    	<td><%= group.priority %></td>
		    	<td><%= group.name %></td>
		    	<td><%= group.ac_fields.count %></td>
		    	<td> 
		     	<%= link_to '<span class="icon icon-edit">'.html_safe+l(:edit), edit_project_ac_group_path(group, :project_id => @project, :tracker_id => tracker.id) %>
				<%= link_to '<span class="icon icon-del">'.html_safe+l(:delete), project_ac_group_path(group, :project_id => @project), :confirm => "¿Desea eliminar este tipo de agrupación?", :method => :delete %>
				</td>
		    </tr>
			<% end %>
		<% else %>
			<tr class="<%= cycle("odd", "even") %>">
			    <td colspan="4"><i><%= l(:'group.not_groups_found') %></i></td>
			</tr>
		<% end %>
	    
	</tbody>
	</table>
</fieldset>
	<br>
<% end %>

app/views/ac_groups/new.html.erb
<%= render "ac_groups/partials/form" %>

app/views/ac_groups/partials/_form.html.erb
<%= csrf_meta_tag %>
<% content_for :header_tags do %>
   <%= javascript_include_tag "/ac_groups.js", :plugin => 'redmine_agrupacion_campos' %>
   <%= stylesheet_link_tag "/ac_groups.css", :plugin => 'redmine_agrupacion_campos', :media => "screen" %>
<% end %>

<h2><%= l(:'group.new_group_message') + @tracker.name %></h2>

<%= form_for [@project, @group] do |f| %>
	<div class="d_group">
		<div class="d_field">
			<div><%= f.label l(:'group.name')+": " %></div>
			<%= f.text_field(:name, :size => 30) %>
		</div>

		<div class="d_field d_field_priority">
			<div><%= f.label l(:'group.priority')+": " %></div>
			<%= f.number_field(:priority, :step => 1, class: "group_number_field") %>
		</div>

		<div class="d_field d_field_width">
			<div><%= f.label l(:'group.width')+": " %></div>
			<%= f.select :width, options_for_select([100, 50], :selected => @group.width ) %> %
		</div>

	</div>
	<%= f.hidden_field :tracker_id, :value => @tracker.id %>

	<%= select_tag "select_fields_hidden", options_for_select(@custom_fields_by_tracker),:class => "select_fields_hidden", :style => "visibility: hidden" %>
	<fieldset class="fieldset_fields">
		<legend><b><%= l(:'field.custom_fields') %></b></legend>
		<% if @count_fields != 0 %>
			<% (0...@count_fields).each do |i| %>
				<%= f.fields_for :ac_fields, @field[i] do |j| %>
					<fieldset class= "f_field fieldset_for_field_<%= i %>">
						<div class="d_field">
						<p class="p_field"><%= j.label l(:'field.custom_field')+": " %></p>
						<%= j.select :custom_field_id, options_for_select(@custom_fields_by_tracker, :selected => @field[i][:custom_field_id])  %>
						</div>

						<div class="d_field d_field_priority">
						<p class="p_field"><%= j.label l(:'field.priority')+": " %></p>
						<%= j.number_field(:priority, :step => 1, class: "field_number_field") %>
						</div>

						<div class="d_field d_field_delete">
						<%= link_to '<span class="icon icon-del">'.html_safe+l(:delete), project_ac_group_ac_field_path(@group, @field[i], :tracker_id => @tracker.id,:project_id => @project), :confirm => "¿Desea eliminar este campo personalizado?", :method => :delete if !@field[i].new_record? %>
						</div>

					</fieldset>
				<% end %>
			<% end %>
		<% end %>

		<div class="btn_add_field">
		    <a><span class="icon icon-add add_field" data-count="<%= @count_fields %>"><%= l(:'field.add') %></span></a>
		</div>
	</fieldset>

	<div>
	<%= f.submit l(:save), class: "btn_save_group",style: "float: left" %>
	</div>
<% end %>
<%= button_to l(:back), project_ac_groups_path(:project_id => @project), :method => :get %>

app/views/issues/partials/_fields_fieldset.html.erb
<%= csrf_meta_tag %>
<% content_for :header_tags do %>
   <%= stylesheet_link_tag "/edit_fieldsets.css", :plugin => 'redmine_agrupacion_campos', :media => "screen" %>
<% end %>

<% groups = @issue.tracker.ac_groups 
 editable_values = @issue.editable_custom_field_values 
 values = @issue.custom_field_values
 map_values = values.index_by(&:custom_field_id) 
 cf_used = [] %>

	<% if groups.count > 0 && @project.module_enabled?(:agrupacion_de_campos)%>

		<!-- Muestra los campos personalizados que estan asignados a un grupo -->
		<% groups.order("priority ASC").each do |group| %>
			<% if group.ac_fields.present? %>
				<fieldset class='fieldset_ac_group' style='width: <%= group.width - 5 %>%;'>
					<legend id='<%= group.name %>'><%= group.name %></legend>
					<% group.ac_fields.order("priority ASC").each do |cf| %>
						<% if map_values.keys.include?(cf.custom_field_id) %>
							<% cf_used << cf.custom_field_id %>
		                    <% value = map_values[cf.custom_field_id] %>
							<p class="edit_field">
			                    <% if editable_values.include? value %>
										<%= custom_field_tag_with_label :issue, value, :required => @issue.required_attribute?(value.custom_field_id) %>
			                    <% else %>
			                    		<%= custom_field_tag_with_label_disabled :issue, value, :required => @issue.required_attribute?(value.custom_field_id) %>
			                    <% end %>
							</p>
						<% end %>
					<% end %>
				</fieldset>
			<% end %>
		<% end %>

		<!-- Muestra los campos personalizados que no estan asignados a un grupo -->
		<% cf_used.uniq! %>

        <% values.compact.each do |value| %>
            <% if !cf_used.include?(value.custom_field_id) %>
				<p class="edit_field">
					<% if editable_values.include? value %>
							<%= custom_field_tag_with_label :issue, value, :required => @issue.required_attribute?(value.custom_field_id) %>
                    <% else %>
                    		<%= custom_field_tag_with_label_disabled :issue, value, :required => @issue.required_attribute?(value.custom_field_id) %>
                    <% end %>
				</p>
            <% end %>
        <% end %>

	<% else %>
		<%= render :partial => 'issues/form_custom_fields', :issue => @issue %>
	<% end %>